- name: Create folders
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
    url: http://127.0.0.1:9090/
    user: admin
    password: "{{jenkins_password}}"
  loop: "{{ folders}}"
  
- name: Create Muliple branch Pipelines jobs
  ansible.builtin.include_tasks: mbranch-pipeline.yml
  loop: "{{pipeline_jobs}}"

- name: Create Single branch Pipelines jobs
  ansible.builtin.include_tasks: sbranch-pipeline.yml
  loop: "{{sbranch-pipeline_jobs}}"
 
 