- name: Create folders
  community.general.jenkins_job:
    config: "{{ lookup('file', '/templates/folder.xml') }}"
    name: "{{item}}"
    url: http://3.89.146.233:8080
    user: admin
    password: "{{jenkins_password}}"
  loop: "{{ folders}}"
  
- name: Create Pipelines jobs
  ansible.builtin.include_tasks: pipeline.yml
  loop: "{{pipeline_jobs}}"
 