# - name: Create folders
#   community.general.jenkins_job:
#     config: "{{ lookup('file', '/templates/folder.yml') }}"
#     name: "{{item}}"
#     url: http://172.31.47.36:8080
#     user: admin
#     password: "{{jenkins_password}}"
#   loop:
#    - "CIpipelines"
#    - vars:
#     Template: folder.xml
  
- name: Create Pipelines jobs
  ansible.builtin.include_tasks: pipeline.yml
  loop:
   - {name: "frontend", dir: "CIpipelines"}
   - {name: "cart", dir: "CIpipelines"}
   - {name: "catalogue", dir: "CIpipelines"}
   - {name: "user", dir: "CIpipelines"}
   - {name: "payment", dir: "CIpipelines"}
   - {name: "shipping", dir: "CIpipelines"}